version: 2
updates:
  - package-ecosystem: npm
    directory: '/src/Resources/app/administration'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build: '
    groups:
      all:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*jest*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: '/src/Resources/app/storefront'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build: '
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/tests/acceptance'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build: '
    groups:
      all:
        patterns:
          - '*'
