framework:
  exceptions:
    Swag\PayPal\Checkout\Exception\OrderFailedException:
      log_level: notice
    Swag\PayPal\Checkout\PUI\Exception\PaymentInstructionsNotReadyException:
      log_level: notice
    Swag\PayPal\OrdersApi\Administration\Exception\OrderNotFoundException:
      log_level: notice
    Swag\PayPal\PaymentsApi\Administration\Exception\PaymentNotFoundException:
      log_level: notice
    Swag\PayPal\Checkout\Exception\OrderAmountZeroException:
      log_level: notice
    Swag\PayPal\Dispute\Exception\NotAuthorizedException:
      log_level: notice

  http_client:
    scoped_clients:
      paypal.base-client:
        scope: https\://api\-m\.(sandbox\.)?paypal\.com/
        max_duration: 30
        retry_failed:
          max_retries: 3
          delay: 1000
          multiplier: 2
          jitter: 0.1
          http_codes:
            0: ['GET', 'HEAD', 'OPTIONS']
            429: ['GET', 'HEAD', 'OPTIONS']
            502: ['GET', 'HEAD', 'OPTIONS']
            503: ['GET', 'HEAD', 'OPTIONS']
