name: Bug report 🐛
description: Errors or flaws in the code are leading to incorrect or unexpected behavior.
type: Bug
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: shopware-version
      attributes:
          label: Shopware Version
          description: Please specify your Shopware version (e.g. 6.6.10.4). If you're using Shopware Cloud, simply type "cloud".
      validations:
          required: true
    - type: input
      id: paypal-version
      attributes:
          label: PayPal plugin version
          description: Please specify your PayPal plugin version (e.g. 9.7.4). If you're using Shopware Cloud, simply type "cloud".
      validations:
          required: true
    - type: textarea
      id: actual-behaviour
      attributes:
          label: Actual behaviour
          description: Please describe the issue
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected behaviour
          description: What did you expect to happen?
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: How to reproduce & Environment
          description: Tell us how the bug can be reproduced. Are you testing this in Sandbox or with a live account? Have you disabled your theme and/or other plugins?
      validations:
          required: true
