# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Setup SwagPayPal
description: "Setup steps for SwagPayPal"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  install-admin:
    default: "false"
    required: false
    description: "Should we install the Administration of shopware"
  install-commercial:
    default: "false"
    required: false
    description: "Should we install SwagCommercial"
  install-storefront:
    default: "false"
    required: false
    description: "Should we install the Storefront of shopware"
  mysql-version:
    default: "builtin"
    required: false
    description: "Which MySQL version should be used"
  php-version:
    default: "8.2"
    required: false
    description: "Which PHP version should be used"
  shopware-version:
    default: "6.5.x"
    required: false
    description: "Which version/branch of shopware should be used"

runs:
  using: composite
  steps:
    - uses: shopware/octo-sts-action@main
      id: octo-sts
      continue-on-error: true
      with:
        scope: shopware
        identity: ${{ github.event.repository.name }}

    - name: Ignore audit
      if: ${{ inputs.shopware-version != 'trunk' }}
      shell: bash
      run: |
        mkdir -p ~/.config/composer
        yq e -n -o=json '.config.audit.block-insecure=false' > ~/.config/composer/config.json

    - name: Prepare dependency list
      id: dependency-list
      shell: bash
      run: |
        REPOS='{
            "${{ github.event.repository.name }}": {
              "type": "path",
              "url": "custom/plugins/${{ github.event.repository.name }}",
              "symlink": true
            }
        }'

        if [ -x "${{ steps.octo-sts.outputs.token }}" ]; then
            echo "deps='[]'" >> "$GITHUB_OUTPUT"
            echo "repos=$(echo $REPOS | jq -c .)" >> "$GITHUB_OUTPUT"

            exit 0
        fi

        REPOS=$(jq -s 'add' <(echo $REPOS) <(echo '{
            "SwagCmsExtensions": {
              "type": "path",
              "url": "custom/plugins/SwagCmsExtensions",
              "symlink": true
            }
        }'))

        DEPS='[
            {
              "name":"SwagCmsExtensions",
              "repo": "https://github.com/shopware/SwagCmsExtensions.git",
              "branch": "6.5.x",
              "token": "${{ steps.octo-sts.outputs.token }}"
            }
          ]'

        REPOS='{
            "${{ github.event.repository.name }}": {
              "type": "path",
              "url": "custom/plugins/${{ github.event.repository.name }}",
              "symlink": true
            },
            "SwagCmsExtensions": {
              "type": "path",
              "url": "custom/plugins/SwagCmsExtensions",
              "symlink": true
            }
          }'

        if [[ "${{ inputs.install-commercial }}" == "true" ]]; then
          DEPS=$(jq -s 'add' <(echo $DEPS) <(echo '[
            {
              "name":"SwagCommercial",
              "repo": "https://github.com/shopware/SwagCommercial.git",
              "branch": "${{ inputs.shopware-version }}",
              "token": "${{ steps.octo-sts.outputs.token }}"
            }]'))
          REPOS=$(jq -s 'add' <(echo $REPOS) <(echo '{
            "SwagCommercial": {
              "type": "path",
              "url": "custom/plugins/SwagCommercial",
              "symlink": true
            }
          }'))
        fi
        echo "deps=$(echo $DEPS | jq -c .)" >> "$GITHUB_OUTPUT"
        echo "repos=$(echo $REPOS | jq -c .)" >> "$GITHUB_OUTPUT"
    - uses: shopware/github-actions/setup-extension@b1d0a9fddcf38cd550f328ea00e1beb7536fa494
      with:
        extensionName: ${{ github.event.repository.name }}
        mysqlVersion: ${{ inputs.mysql-version }}
        shopwareVersion: ${{ inputs.shopware-version }}
        phpVersion: ${{ inputs.php-version }}
        node-version: 18.x
        npm-version: 9
        keep-composer-tools: true
        install: true
        install-admin: ${{ inputs.install-admin }}
        install-storefront: ${{ inputs.install-storefront }}
        dependencies: ${{ steps.dependency-list.outputs.deps }}
        extraRepositories: ${{ steps.dependency-list.outputs.repos }}

    - name: Prepare Administration
      shell: bash
      if: ${{ inputs.install-admin == 'true' }}
      run: |
        bin/console bundle:dump
        composer admin:generate-entity-schema-types
