# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Setup SwagPayPal
description: "Setup steps for SwagPayPal"
author: "shopware AG"
branding:
  color: "blue"
  icon: "download"

inputs:
  install-admin:
    default: "false"
    required: false
    description: "Should we install the Administration of shopware"
  install-commercial:
    default: "false"
    required: false
    description: "Should we install SwagCommercial"
  install-storefront:
    default: "false"
    required: false
    description: "Should we install the Storefront of shopware"
  mysql-version:
    default: "builtin"
    required: false
    description: "Which MySQL version should be used"
  php-version:
    default: "8.2"
    required: false
    description: "Which PHP version should be used"
  shopware-version:
    default: "trunk"
    required: false
    description: "Which version/branch of shopware should be used"
  extension-zip:
    description: "Artifact (extension zip archive) to download; Setting this will prevent a checkout of the extension and download the referenced archive instead"
    required: false
  env:
    description: "Environment for Shopware"
    required: true
    default: "test"

runs:
  using: composite
  steps:
    - uses: octo-sts/action@main
      id: octo-sts
      with:
        scope: shopware
        identity: ${{ github.event.repository.name }}
    - name: Prepare dependency list
      id: dependency-list
      shell: bash
      run: |
        DEPS='[
            {
                "name":"SwagCmsExtensions",
                "repo": "https://github.com/shopware/SwagCmsExtensions.git",
                "token": "${{ steps.octo-sts.outputs.token }}"
            }
        ]'

        # @deprecated tag:v11.0.0 - Will be removed
        if [ "${{ inputs.shopware-version }}" = "6.7.0.0" ]; then
            # require last ref of SwagCmsExtensions before requiring ~6.7.3
            DEPS=$(echo "$DEPS" | jq '[.[0] + {"branch": "0b5f9df838541c47f67f3d4af14d94f01fa0b189"}]')
        fi

        REPOS='{
            "${{ github.event.repository.name }}": {
              "type": "path",
              "url": "custom/plugins/${{ github.event.repository.name }}",
              "symlink": true
            },
            "SwagCmsExtensions": {
              "type": "path",
              "url": "custom/plugins/SwagCmsExtensions",
              "symlink": true
            }
        }'

        if [[ "${{ inputs.install-commercial }}" == "true" ]]; then
            DEPS=$(jq -s 'add' <(echo $DEPS) <(echo '[
                {
                    "name":"SwagCommercial",
                    "repo": "https://github.com/shopware/SwagCommercial.git",
                    "branch": "${{ inputs.shopware-version }}",
                    "token": "${{ steps.octo-sts.outputs.token }}"
                }
            ]'))

            REPOS=$(jq -s 'add' <(echo $REPOS) <(echo '{
                "SwagCommercial": {
                    "type": "path",
                    "url": "custom/plugins/SwagCommercial",
                    "symlink": true
                }
            }'))
        fi

        echo "deps=$(echo $DEPS | jq -c .)" >> "$GITHUB_OUTPUT"
        echo "repos=$(echo $REPOS | jq -c .)" >> "$GITHUB_OUTPUT"

    - uses: shopware/github-actions/setup-extension@main
      with:
        extension-zip: ${{ inputs.extension-zip }}
        extensionName: ${{ github.event.repository.name }}
        mysqlVersion: ${{ inputs.mysql-version }}
        shopwareVersion: ${{ inputs.shopware-version }}
        phpVersion: ${{ inputs.php-version }}
        install: true
        install-admin: ${{ inputs.install-admin }}
        install-storefront: ${{ inputs.install-storefront }}
        env: ${{ inputs.env }}
        dependencies: ${{ steps.dependency-list.outputs.deps }}
        extraRepositories: ${{ steps.dependency-list.outputs.repos }}
        keep-composer-tools: true
    - name: Prepare Administration
      shell: bash
      if: ${{ inputs.install-admin == 'true' }}
      run: |
        bin/console bundle:dump
        composer admin:generate-entity-schema-types
