name: Acceptance

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  check:
      if: always()
      needs: [eslint]
      runs-on: ubuntu-latest
      steps:
        - uses: re-actors/alls-green@v1.2.2
          with:
            jobs: ${{ toJSON(needs) }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SwagPayPal
        uses: actions/checkout@v5
        with:
          path: custom/plugins/${{ github.event.repository.name }}

      - name: Setup SwagPayPal
        uses: ./custom/plugins/SwagPayPal/.github/actions/setup-paypal
        with:
          install-admin: false
          install-storefront: false
          install-commercial: false

      - name: Install dependencies
        working-directory: ./custom/plugins/SwagPayPal/tests/acceptance
        run: npm ci

      - name: Run ESLint
        working-directory: ./custom/plugins/SwagPayPal/tests/acceptance
        run: npm run lint
