name: Admin
on:
  push:
    branches:
      - trunk
  pull_request:
  # TODO: paths: src/Resources/app/administration
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@main
        id: octo-sts
        with:
          scope: shopware
          identity: ${{ github.event.repository.name }}
      - uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          install: true
          installAdmin: true
          dependencies: |
            [
              {
                "name":"SwagCommercial",
                "repo": "https://github.com/shopware/SwagCommercial.git",
                "token": "${{ steps.octo-sts.outputs.token }}"
              },
              {
                "name":"SwagCmsExtensions",
                "repo": "https://github.com/shopware/SwagCmsExtensions.git",
                "token": "${{ steps.octo-sts.outputs.token }}"
              }
            ]
          extraRepositories: |
            {
              "${{ github.event.repository.name }}": {
                "type": "path",
                "url": "custom/plugins/${{ github.event.repository.name }}",
                "symlink": true
              },
              "SwagCommercial": {
                "type": "path",
                "url": "custom/plugins/SwagCommercial",
                "symlink": true
              },
              "SwagCmsExtensions": {
                "type": "path",
                "url": "custom/plugins/SwagCmsExtensions",
                "symlink": true
              }
            }
      - name: Prepare ESLint
        run: |
          bin/console bundle:dump
          composer admin:generate-entity-schema-types
      - name: Run ESLint
        env:
          ADMIN_PATH: ${{ github.workspace }}/src/Administration/Resources/app/administration
        working-directory: custom/plugins/${{ github.event.repository.name }}/src/Resources/app/administration
        run: |
          npm run lint-fix
          npm run lint
  jest:
    uses: shopware/github-actions/.github/workflows/admin-jest.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      uploadCoverage: false
