name: Admin
on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - src/Resources/app/administration/**/*
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  check:
      if: always()
      needs: [eslint, jest]
      runs-on: ubuntu-latest
      steps:
        - uses: re-actors/alls-green@v1.2.2
          with:
            jobs: ${{ toJSON(needs) }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SwagPayPal
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ github.event.repository.name }}
      - name: Setup SwagPayPal
        uses: ./custom/plugins/SwagPayPal/.github/actions/setup-paypal
        with:
          install-admin: true
      - name: Run ESLint
        env:
          ADMIN_PATH: ${{ github.workspace }}/src/Administration/Resources/app/administration
        working-directory: custom/plugins/${{ github.event.repository.name }}
        run: composer run lint:admin:ci

  jest:
    uses: shopware/github-actions/.github/workflows/admin-jest.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      uploadCoverage: false
