name: integration

on:
  push:
    branches:
      - 6.6.x
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  check:
      if: always()
      needs: [build-zip, test-install-zip, phpunit]
      runs-on: ubuntu-latest
      steps:
        - uses: re-actors/alls-green@v1.2.2
          with:
            jobs: ${{ toJSON(needs) }}

  build-zip:
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - name: Build and validate zip
        uses: shopware/github-actions/build-zip@main
        with:
          extensionName: ${{ github.event.repository.name }}

  test-install-zip:
    needs: build-zip
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORM_BRANCH: ["v6.6.0.0", "6.6.x"]
    steps:
      - name: Checkout SwagPayPal
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ github.event.repository.name }}

      - name: Test install zip
        uses: ./custom/plugins/SwagPayPal/.github/actions/setup-paypal
        with:
          extension-zip: ${{ needs.build-zip.outputs.artifact-url }}
          shopware-version: ${{ matrix.PLATFORM_BRANCH }}

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MYSQL_IMAGE: ["mysql:8.0", "mariadb:10.11"]
        PLATFORM_BRANCH: ["v6.6.0.0", "6.6.x"]
        PHP_VERSION: ["8.2", "8.3"]
        WITH_COMMERCIAL: [true, false]
    env:
      REDIS_URL: redis://localhost:6379
    services:
      redis:
        image: redis:alpine
        ports:
          - "6379:6379"
    steps:
      - name: Checkout SwagPayPal
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ github.event.repository.name }}

      - name: Setup SwagPayPal
        uses: ./custom/plugins/SwagPayPal/.github/actions/setup-paypal
        with:
          install-commercial: ${{ matrix.WITH_COMMERCIAL }}
          install-admin: true
          install-storefront: true
          mysql-version: ${{ matrix.MYSQL_IMAGE }}
          php-version: ${{ matrix.PHP_VERSION }}
          shopware-version: ${{ matrix.PLATFORM_BRANCH }}

      - name: Run PHPUnit
        working-directory: custom/plugins/${{ github.event.repository.name }}
        run: |
          composer dump-autoload --dev
          php -d pcov.enabled=1 -d pcov.directory=$PWD/src -d pcov.exclude='~(vendor|tests|node_modules)~' \
            ${GITHUB_WORKSPACE}/vendor/bin/phpunit \
            --configuration phpunit.xml.dist \
            --log-junit ${GITHUB_WORKSPACE}/phpunit.junit.xml \
            --coverage-cobertura ${GITHUB_WORKSPACE}/cobertura.xml \
            --coverage-text
