name: Release to Store

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/store-release@main
        with:
          extensionName: ${{ github.event.repository.name }}
          clientId: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_ID }}
          clientSecret: ${{ secrets.SHOPWARE_CLI_ACCOUNT_CLIENT_SECRET }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
