name: storefront

on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - src/Resources/app/storefront/**/*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SwagPayPal
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ github.event.repository.name }}

      - name: Setup SwagPayPal
        uses: ./custom/plugins/SwagPayPal/.github/actions/setup-paypal
        with:
          install-commercial: true
          install-storefront: true

      - name: Run ESLint
        env:
          STOREFRONT_PATH: ${{ github.workspace }}/src/Storefront/Resources/app/storefront
        working-directory: custom/plugins/${{ github.event.repository.name }}
        run: composer lint:storefront:ci
